### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ldellisola** [nor0x/Dots#14]
Hey!

Dots looks great, I have been thinking about helping out fixing some bugs I found but I cannot get it to build on MacOS. Could you write a small "Development" section in the readme explaining how to set the build process?

I installed the mac catalyst workload but I'm stuck on the following error:
> Xamarin.Shared.targets(1738, 3): Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools'. Please update your Apple SDK location in Rider's preferences (Preferences | Build, Execution, Deployment | Apple Platforms).

CommandLineTools is installed on that directory but I think I'm missing some dependency to build it (maybe I need xcode?).

**Comment by nor0x** [comment]
Hi @ldellisola - glad you like it, i'm already working on an update to Dots that will make publishing the app easier.
I will then also update the Readme with a proper Development guide.

in the meantime - for building on macOS please make sure that you have Xcode installed - i'm not 100% sure but it could be that you also need to have the "Xcode command line developer tools" you can get them by executing `xcode-select --install` in your terminal

**Comment by nor0x** [comment]
see #24
