### ISSUE TITLE
Cannot run Dots 2.0.0: "Dots" is damaged and can't be opened

### ISSUE THREAD

**Issue by mauroservienti** [nor0x/Dots#25]
I juts downloaded 2.0.0, and I got the following error (macOS Sonoma):

![image](https://github.com/nor0x/Dots/assets/1325611/706239d2-ae1f-470c-9652-4b2f728fed79)

**Comment by nor0x** [comment]
thanks for trying the app. i will have a look at the issue soon as i'm back to my M1 mac. Does building the project from source work for you?

also i will check notarization for the app here #26

**Comment by mauroservienti** [comment]
Thanks for getting back to me. No I've not tried building myself, I'll give it a go and let you know.

**Comment by mauroservienti** [comment]
`dotnet build` fails with the following error:

> error NETSDK1191: A runtime identifier for the property 'SelfContained' couldn't be inferred. Specify a rid explicitly. [/Users/mauroservienti/dev/nor0x/Dots/src/Dots.csproj]

I have Xcode 15.0.1

**Comment by nor0x** [comment]
in you case (macOS arm64 architecture) the command would be

`dotnet run -r osx-arm64`

**Comment by mauroservienti** [comment]
That worked. I was able to start the application.
