### ISSUE TITLE
Always stuck in the loading interface

### ISSUE THREAD

**Issue by seamusic** [nor0x/Dots#31]
wait a long time, but still in loading.

windows 11 + 2.0.2 64bit

![image](https://github.com/nor0x/Dots/assets/172009/cb3f4761-0260-468e-a2ed-3a44a8754df5)

![image](https://github.com/nor0x/Dots/assets/172009/2c5b175b-9048-4bb5-9b24-4c0ab61ae085)

**Comment by seamusic** [comment]
resolved after waiting for more than 1 minute

**Comment by nor0x** [comment]
thanks for the info @seamusic. A progress indicator is already on my ToDo list and i'm thinking about lazy loading the SDKs for increased responsiveness
