### ISSUE TITLE
[Windows] Publishing 🥲

### ISSUE THREAD

**Issue by nor0x** [nor0x/Dots#5]

**Comment by alexeygritsenko** [comment]
hi, interesting project. where can i download the installer for windows?

**Comment by nor0x** [comment]
unfortunately the story for Windows publishing in the underlying framework is terrible to non-existent

i will try to make it available as soon as possible, but until then please upvote the following issue
https://github.com/dotnet/maui/issues/10564

**Comment by nor0x** [comment]
see #24
